name: Deploy packages
on:
  push:
    branches:
      - main
    paths:
      - "pegasys-helpers/**"
      - ".github/**"
    tags:
      - "**"
jobs:
  build:
    permissions:
      id-token: write
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Replace properties
        run: |
          npm install
          npm run build
        working-directory: ./pegasys-helpers
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./pegasys-helpers/dist/
